# Generated by Django 3.1 on 2020-08-31 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('PP', 'Passport'), ('AD', 'Adhar Card'), ('DL', 'Driving License')], default='PP', max_length=100)),
                ('doc_number', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='datasheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.datasheet'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.ManyToManyField(to='ecom.Profession'),
        ),
    ]
